# Generated by Django 4.2.29 on 2026-03-11 05:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('product', models.CharField(choices=[('taggiq', 'TaggIQ'), ('kritno', 'Kritno'), ('fullypromoted', 'Fully Promoted'), ('other', 'Other')], default='taggiq', max_length=30)),
                ('from_name', models.CharField(default='', help_text='Sender display name', max_length=200)),
                ('from_email', models.EmailField(default='', help_text='Sender email (must be SES-verified)', max_length=254)),
                ('reply_to_email', models.EmailField(blank=True, default='', help_text='Reply-to address', max_length=254)),
                ('sending_enabled', models.BooleanField(default=False, help_text='Master switch for this campaign')),
                ('max_emails_per_day', models.IntegerField(default=15)),
                ('min_gap_minutes', models.IntegerField(default=15)),
                ('max_emails_per_prospect', models.IntegerField(default=5)),
                ('require_sequence_order', models.BooleanField(default=True)),
                ('unsubscribe_footer_html', models.TextField(default='<p style="font-size:12px;color:#999;margin-top:30px;">If you\'d prefer not to hear from us, simply reply with "unsubscribe" and we\'ll remove you immediately.</p>')),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Suppression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('opt_out', 'Opted Out'), ('bounce', 'Bounced'), ('complaint', 'Complaint'), ('manual', 'Manually Added')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'suppressions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=300)),
                ('website', models.URLField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('region', models.CharField(blank=True, default='', max_length=200)),
                ('decision_maker_name', models.CharField(blank=True, default='', max_length=300)),
                ('decision_maker_title', models.CharField(blank=True, default='', max_length=200)),
                ('business_type', models.CharField(blank=True, default='', max_length=100)),
                ('segment', models.CharField(blank=True, choices=[('print_shop', 'Print Shop'), ('promo_distributor', 'Promo Distributor'), ('apparel_embroidery', 'Apparel / Embroidery'), ('mixed', 'Mixed Operations'), ('signs', 'Signs & Display'), ('print_agency', 'Print & Creative Agency')], default='', max_length=30)),
                ('tier', models.CharField(blank=True, choices=[('A', 'Tier A - Hot'), ('B', 'Tier B - Warm'), ('C', 'Tier C - Cool'), ('D', 'Tier D - Park')], default='C', max_length=1)),
                ('score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('engaged', 'Engaged'), ('interested', 'Interested'), ('demo_scheduled', 'Demo Scheduled'), ('design_partner', 'Design Partner'), ('not_interested', 'Not Interested'), ('opted_out', 'Opted Out')], default='new', max_length=20)),
                ('emails_sent', models.IntegerField(default=0)),
                ('last_emailed_at', models.DateTimeField(blank=True, null=True)),
                ('current_tools', models.CharField(blank=True, default='', max_length=500)),
                ('pain_signals', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('send_enabled', models.BooleanField(default=True, help_text='Uncheck to block outreach')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'prospects',
                'ordering': ['-score', 'business_name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('body_html', models.TextField()),
                ('sequence_number', models.IntegerField(default=1)),
                ('template_name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='sent', max_length=20)),
                ('ses_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('ab_variant', models.CharField(blank=True, default='', max_length=10)),
                ('triggered_by', models.CharField(default='agent', max_length=50)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='campaigns.campaign')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='campaigns.prospect')),
            ],
            options={
                'db_table': 'email_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['tier', 'status'], name='prospects_tier_9a4ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['email'], name='prospects_email_f91804_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['segment'], name='prospects_segment_7c3202_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prospect',
            unique_together={('campaign', 'email')},
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['prospect', 'sequence_number'], name='email_log_prospec_0d87b1_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['to_email', 'created_at'], name='email_log_to_emai_4d4711_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['campaign', 'ab_variant'], name='email_log_campaig_b724a0_idx'),
        ),
    ]
