# Generated by Django 4.2.29 on 2026-03-11 07:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='follow_up_days',
            field=models.IntegerField(default=5, help_text='Days to wait before sending next sequence email'),
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=500)),
                ('body_html', models.TextField()),
                ('sequence_number', models.IntegerField(default=1)),
                ('template_name', models.CharField(blank=True, default='', max_length=100)),
                ('ab_variant', models.CharField(blank=True, default='', max_length=10)),
                ('send_after', models.DateTimeField(help_text='Do not send before this time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_emails', to='campaigns.campaign')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_emails', to='campaigns.prospect')),
            ],
            options={
                'db_table': 'email_queue',
                'ordering': ['send_after'],
                'indexes': [models.Index(fields=['status', 'send_after'], name='email_queue_status_77dc51_idx'), models.Index(fields=['campaign', 'prospect', 'sequence_number'], name='email_queue_campaig_bbc4d0_idx')],
            },
        ),
    ]
