# Generated by Django 4.2.29 on 2026-03-16 12:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_follow_up_days_emailqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, default='', max_length=300)),
                ('subject', models.CharField(max_length=500)),
                ('body_text', models.TextField(default='')),
                ('message_id', models.CharField(max_length=500, unique=True)),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=500)),
                ('classification', models.CharField(choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('opt_out', 'Opt Out'), ('question', 'Question'), ('out_of_office', 'Out of Office'), ('bounce', 'Bounce'), ('other', 'Other')], default='other', max_length=20)),
                ('replied_to_sequence', models.IntegerField(blank=True, null=True)),
                ('needs_reply', models.BooleanField(default=False)),
                ('replied', models.BooleanField(default=False)),
                ('reply_sent_at', models.DateTimeField(blank=True, null=True)),
                ('status_updated', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField()),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_emails', to='campaigns.campaign')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_emails', to='campaigns.prospect')),
            ],
            options={
                'db_table': 'inbound_emails',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['from_email'], name='inbound_ema_from_em_50ac9b_idx'), models.Index(fields=['classification', 'needs_reply'], name='inbound_ema_classif_2f435d_idx')],
            },
        ),
    ]
