# Generated by Django 4.2.29 on 2026-03-16 13:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_inboundemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='auto_reply_enabled',
            field=models.BooleanField(default=False, help_text='Enable autonomous auto-replies for interested/question/other classifications'),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='auto_replied',
            field=models.BooleanField(default=False, help_text='True if reply was sent by auto-reply system'),
        ),
        migrations.CreateModel(
            name='ReplyTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification', models.CharField(choices=[('interested', 'Interested'), ('question', 'Question'), ('other', 'Other')], max_length=20)),
                ('subject_template', models.CharField(default='Re: {{ORIGINAL_SUBJECT}}', help_text='Subject line template. Variables: {{ORIGINAL_SUBJECT}}', max_length=500)),
                ('body_html_template', models.TextField(help_text='HTML body template. Variables: {{FNAME}}, {{COMPANY}}, {{CITY}}, {{SEGMENT}}, {{ORIGINAL_SUBJECT}}, {{ORIGINAL_BODY_SHORT}}')),
                ('is_active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_templates', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'reply_templates',
                'ordering': ['campaign', 'classification'],
                'unique_together': {('campaign', 'classification')},
            },
        ),
    ]
