# Generated by Django 4.2.29 on 2026-03-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_reply_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='best_practices_group',
            field=models.BooleanField(default=False, help_text='Member of BNI best practices community group'),
        ),
    ]
