# Generated by Django 4.2.29 on 2026-03-19 04:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_add_best_practices_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imap_host', models.CharField(default='imappro.zoho.eu', max_length=200)),
                ('imap_port', models.IntegerField(default=993)),
                ('imap_email', models.EmailField(help_text='Email address to check for replies', max_length=254)),
                ('imap_password', models.CharField(max_length=500)),
                ('smtp_host', models.CharField(default='smtppro.zoho.eu', max_length=200)),
                ('smtp_port', models.IntegerField(default=465)),
                ('smtp_email', models.EmailField(help_text='Email address to send replies from', max_length=254)),
                ('smtp_password', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Enable monitoring for this mailbox')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('campaign', models.OneToOneField(help_text='Campaign this mailbox monitors replies for', on_delete=django.db.models.deletion.CASCADE, related_name='mailbox', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'mailbox_configs',
                'ordering': ['campaign__name'],
            },
        ),
    ]
