# Generated by Django 4.2.29 on 2026-03-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_mailbox_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='follow_up_after',
            field=models.DateField(blank=True, help_text='Date to follow up with this prospect', null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('engaged', 'Engaged'), ('interested', 'Interested'), ('demo_scheduled', 'Demo Scheduled'), ('design_partner', 'Design Partner'), ('not_interested', 'Not Interested'), ('opted_out', 'Opted Out'), ('follow_up_later', 'Follow Up Later')], default='new', max_length=20),
        ),
    ]
