# Generated by Django 4.2.29 on 2026-04-08 04:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_add_follow_up_later_status_and_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='calling_enabled',
            field=models.BooleanField(default=False, help_text='Enable outbound calling for this campaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='max_calls_per_day',
            field=models.IntegerField(default=20, help_text='Max calls per day for this campaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='max_calls_per_prospect',
            field=models.IntegerField(default=3, help_text='Max call attempts per prospect'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='min_gap_call_minutes',
            field=models.IntegerField(default=1, help_text='Min minutes between calls'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='vapi_assistant_id',
            field=models.CharField(blank=True, default='', help_text='Vapi assistant ID for outbound calls', max_length=100),
        ),
        migrations.AddField(
            model_name='prospect',
            name='calls_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prospect',
            name='last_called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('answered', 'Answered'), ('voicemail', 'Voicemail'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed')], default='placed', max_length=20)),
                ('disposition', models.CharField(choices=[('interested', 'Interested'), ('demo_booked', 'Demo Booked'), ('send_info', 'Send Info'), ('callback_requested', 'Callback Requested'), ('not_interested', 'Not Interested'), ('already_using_tool', 'Already Using Tool'), ('wrong_number', 'Wrong Number'), ('gatekeeper_blocked', 'Gatekeeper Blocked'), ('do_not_call', 'Do Not Call'), ('pending', 'Pending')], default='pending', max_length=30)),
                ('call_duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('vapi_call_id', models.CharField(blank=True, default='', help_text='Vapi call ID', max_length=100)),
                ('recording_url', models.URLField(blank=True, default='')),
                ('transcript', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='', help_text='AI-generated call summary')),
                ('email_captured', models.EmailField(blank=True, default='', help_text='Email captured during call', max_length=254)),
                ('callback_time', models.CharField(blank=True, default='', help_text='Requested callback time', max_length=100)),
                ('current_tools', models.CharField(blank=True, default='', help_text='Tools prospect mentioned', max_length=500)),
                ('pain_signals', models.TextField(blank=True, default='', help_text='Pain points mentioned')),
                ('triggered_by', models.CharField(default='management_command', max_length=50)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='campaigns.campaign')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='campaigns.prospect')),
            ],
            options={
                'db_table': 'call_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prospect', 'created_at'], name='call_log_prospec_ffea9b_idx'), models.Index(fields=['campaign', 'status'], name='call_log_campaig_fde58e_idx'), models.Index(fields=['vapi_call_id'], name='call_log_vapi_ca_e82b4c_idx')],
            },
        ),
    ]
