# Generated by Django 4.2.29 on 2026-04-08 05:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaign_calling_enabled_campaign_max_calls_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calls_analyzed', models.IntegerField(default=0)),
                ('date_range', models.CharField(blank=True, default='', max_length=100)),
                ('answer_rate', models.FloatField(default=0, help_text='% of calls answered')),
                ('interest_rate', models.FloatField(default=0, help_text='% of answered calls showing interest')),
                ('demo_rate', models.FloatField(default=0, help_text='% of answered calls booking demo')),
                ('top_objections', models.TextField(blank=True, default='', help_text='Most common objections')),
                ('drop_off_points', models.TextField(blank=True, default='', help_text='Where prospects disengage')),
                ('working_hooks', models.TextField(blank=True, default='', help_text='What language/hooks get engagement')),
                ('prospect_language', models.TextField(blank=True, default='', help_text='Actual words prospects use to describe pain')),
                ('suggestions', models.TextField(blank=True, default='', help_text='Specific script change recommendations')),
                ('suggested_prompt', models.TextField(blank=True, default='', help_text='Full suggested system prompt')),
                ('prompt_applied', models.BooleanField(default=False, help_text='Whether this prompt was pushed to Vapi')),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_insights', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'script_insights',
                'ordering': ['-created_at'],
            },
        ),
    ]
