# Generated by Django 4.2.29 on 2026-04-08 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0009_scriptinsight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='campaigns.organization')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['organization', 'name'],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='batch_size',
            field=models.IntegerField(default=100, help_text='Max prospects to process per run'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='inter_send_delay_max',
            field=models.IntegerField(default=60, help_text='Max seconds between sends'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='inter_send_delay_min',
            field=models.IntegerField(default=5, help_text='Min seconds between sends'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='priority_cities',
            field=models.CharField(blank=True, default='', help_text='Comma-separated cities to send first', max_length=500),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_window_days',
            field=models.CharField(default='0,1,2,3,4', help_text='Comma-separated weekday numbers (0=Mon)', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_window_end_hour',
            field=models.IntegerField(default=17, help_text='Latest hour to send (0-23)'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_window_start_hour',
            field=models.IntegerField(default=10, help_text='Earliest hour to send (0-23)'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_window_timezone',
            field=models.CharField(default='Europe/Dublin', help_text='Timezone for send window', max_length=50),
        ),
        migrations.AddField(
            model_name='scriptinsight',
            name='baseline_answer_rate',
            field=models.FloatField(blank=True, help_text='Answer rate before prompt change', null=True),
        ),
        migrations.AddField(
            model_name='scriptinsight',
            name='baseline_interest_rate',
            field=models.FloatField(blank=True, help_text='Interest rate before prompt change', null=True),
        ),
        migrations.AddField(
            model_name='scriptinsight',
            name='improvement_measured',
            field=models.BooleanField(default=False, help_text='Whether post-change measurement was done'),
        ),
        migrations.AddField(
            model_name='scriptinsight',
            name='measured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scriptinsight',
            name='post_change_answer_rate',
            field=models.FloatField(blank=True, help_text='Answer rate 1 week after change', null=True),
        ),
        migrations.AddField(
            model_name='scriptinsight',
            name='post_change_interest_rate',
            field=models.FloatField(blank=True, help_text='Interest rate 1 week after change', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='product',
            field=models.CharField(choices=[('taggiq', 'TaggIQ'), ('kritno', 'Kritno'), ('fullypromoted', 'Fully Promoted'), ('other', 'Other')], default='taggiq', help_text='Legacy - use product_ref FK instead', max_length=30),
        ),
        migrations.AlterField(
            model_name='suppression',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.CharField(choices=[('email_reply', 'Email Reply Generation'), ('call_analysis', 'Call Transcript Analysis'), ('script_improvement', 'Script Improvement'), ('classification', 'Email Classification')], max_length=30)),
                ('name', models.CharField(help_text='Human name, e.g. "TaggIQ Email Expert v3"', max_length=300)),
                ('system_prompt', models.TextField(help_text='Full system prompt for the AI model')),
                ('model', models.CharField(default='claude-sonnet-4-6', help_text='Model ID to use', max_length=100)),
                ('max_tokens', models.IntegerField(default=4096)),
                ('temperature', models.FloatField(default=0.7)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1, help_text='Increment on each update for tracking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_templates', to='campaigns.product')),
            ],
            options={
                'db_table': 'prompt_templates',
                'ordering': ['product', 'feature', '-version'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='product_ref',
            field=models.ForeignKey(blank=True, help_text='Product this campaign belongs to (new FK)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.product'),
        ),
        migrations.AddField(
            model_name='suppression',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product scope. Null = global suppression across all products.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppressions', to='campaigns.product'),
        ),
        migrations.AlterUniqueTogether(
            name='suppression',
            unique_together={('email', 'product')},
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.IntegerField(help_text='Sequence number (1-5)')),
                ('ab_variant', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('subject_template', models.CharField(help_text='Subject line. Variables: {{FNAME}}, {{COMPANY}}, {{CITY}}, {{YEAR}}, {{SEGMENT}}', max_length=500)),
                ('body_html_template', models.TextField(help_text='HTML body. Variables: {{FNAME}}, {{COMPANY}}, {{CITY}}, {{YEAR}}, {{SEGMENT}}')),
                ('template_name', models.CharField(help_text='Identifier logged in EmailLog.template_name', max_length=100)),
                ('sequence_label', models.CharField(blank=True, default='', help_text='Human label, e.g. "Peer Story"', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'email_templates',
                'ordering': ['campaign', 'sequence_number', 'ab_variant'],
                'unique_together': {('campaign', 'sequence_number', 'ab_variant')},
            },
        ),
        migrations.CreateModel(
            name='CallScript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment', models.CharField(blank=True, choices=[('print_shop', 'Print Shop'), ('promo_distributor', 'Promo Distributor'), ('apparel_embroidery', 'Apparel / Embroidery'), ('mixed', 'Mixed Operations'), ('signs', 'Signs & Display'), ('print_agency', 'Print & Creative Agency')], default='', help_text='Prospect segment. Empty = default script for this campaign.', max_length=30)),
                ('first_message', models.TextField(help_text='Vapi first_message override for this segment')),
                ('is_active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_scripts', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'call_scripts',
                'ordering': ['campaign', 'segment'],
                'unique_together': {('campaign', 'segment')},
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.CharField(choices=[('email_reply', 'Email Reply'), ('call_analysis', 'Call Analysis'), ('script_improvement', 'Script Improvement'), ('classification', 'Classification')], max_length=30)),
                ('model', models.CharField(help_text='Model ID used', max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('latency_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('prompt_version', models.IntegerField(blank=True, help_text='PromptTemplate.version used', null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='campaigns.campaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='campaigns.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='campaigns.product')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='campaigns.prospect')),
            ],
            options={
                'db_table': 'ai_usage_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='ai_usage_lo_organiz_d3c2fc_idx'), models.Index(fields=['product', 'feature'], name='ai_usage_lo_product_9529b4_idx')],
            },
        ),
    ]
