# Generated by Django 4.2.30 on 2026-04-10 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_seed_org_products_link_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='taggiq_user_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('engaged', 'Engaged'), ('interested', 'Interested'), ('demo_scheduled', 'Demo Scheduled'), ('design_partner', 'Design Partner'), ('customer', 'Customer'), ('not_interested', 'Not Interested'), ('opted_out', 'Opted Out'), ('follow_up_later', 'Follow Up Later')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('source', models.CharField(default='taggiq', max_length=50)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'webhook_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'processed'], name='webhook_eve_event_t_f5eefa_idx')],
            },
        ),
    ]
