# Generated by Django 4.2.30 on 2026-04-10 17:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_taggiq_webhook_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('google', 'Google Business')], max_length=20)),
                ('account_name', models.CharField(help_text='Display name (e.g. "TaggIQ LinkedIn Page")', max_length=300)),
                ('page_id', models.CharField(blank=True, default='', help_text='Platform page/org ID', max_length=200)),
                ('access_token', models.TextField(blank=True, default='', help_text='OAuth access token')),
                ('refresh_token', models.TextField(blank=True, default='', help_text='OAuth refresh token (if applicable)')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='campaigns.product')),
            ],
            options={
                'db_table': 'social_accounts',
                'ordering': ['product', 'platform'],
                'unique_together': {('product', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_number', models.IntegerField(help_text='Sequential number within the content plan')),
                ('content', models.TextField(help_text='Post body text')),
                ('hashtags', models.CharField(blank=True, default='', max_length=500)),
                ('link_url', models.URLField(blank=True, default='', help_text='URL to include (as first comment on LinkedIn)')),
                ('media_url', models.URLField(blank=True, default='', help_text='Image/video URL to attach')),
                ('media_description', models.CharField(blank=True, default='', max_length=500)),
                ('pillar', models.CharField(blank=True, default='', help_text='Content pillar category', max_length=50)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='campaigns.product')),
            ],
            options={
                'db_table': 'social_posts',
                'ordering': ['scheduled_date', 'post_number'],
                'unique_together': {('product', 'post_number')},
            },
        ),
        migrations.CreateModel(
            name='SocialPostDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('platform_post_id', models.CharField(blank=True, default='', max_length=200)),
                ('error', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='campaigns.socialaccount')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='campaigns.socialpost')),
            ],
            options={
                'db_table': 'social_post_deliveries',
                'ordering': ['-created_at'],
                'unique_together': {('post', 'account')},
            },
        ),
    ]
