# Generated by Django 4.2.30 on 2026-04-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_move_social_models_to_social_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundemail',
            name='ai_attempt_count',
            field=models.IntegerField(default=0, help_text='How many times the AI reply pipeline has tried to handle this inbound (success or fail).'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='from_name',
            field=models.CharField(blank=True, default='', help_text='Display name for outbound replies, e.g. "Lisa - Fully Promoted Dublin"', max_length=200),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='max_reply_words',
            field=models.IntegerField(default=130, help_text='Hard ceiling on reply body word count (signature excluded). Pre-send block fires above this.'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='signature_name',
            field=models.CharField(blank=True, default='', help_text='First-name anchor for signature stripping in detectors, e.g. "Lisa"', max_length=100),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='warn_reply_words',
            field=models.IntegerField(default=100, help_text='Soft warn threshold for reply length. Logged but not blocked.'),
        ),
    ]
