# Generated by Django 4.2.30 on 2026-04-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_inboundemail_ai_attempt_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='loom_url',
            field=models.TextField(blank=True, default='', help_text='Campaign-level Loom/video URL. Referenced by EmailTemplates via {{LOOM_URL}}.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='use_context_assembler',
            field=models.BooleanField(default=False, help_text='Sprint 6 feature flag. When True, replies/sends inject per-prospect conversation context from Phase 2 services. Defaults False (dark). Flipped manually after shadow eval wins.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='ai_budget_usd_monthly',
            field=models.DecimalField(decimal_places=2, default=500, help_text='Monthly AI spend ceiling in USD. Enforced by ai_budget service.', max_digits=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='ai_usage_current_month_cents',
            field=models.IntegerField(default=0, help_text='Running AI spend for the current month in cents. Reset monthly.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='ai_usage_month_anchor',
            field=models.DateField(blank=True, help_text='First day of the current accounting month. When today > anchor+30d, reset counter.', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='personal_hook',
            field=models.TextField(blank=True, default='', help_text='Pre-written first-line hook for this prospect. Rendered into templates via {{PERSONAL_HOOK}}.'),
        ),
    ]
