# Generated by Django 4.2.29 on 2026-04-13 13:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_sprint6_loom_hook_flag_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusagelog',
            name='brain_version',
            field=models.IntegerField(blank=True, help_text='ProductBrain.version active at call time (Sprint 7)', null=True),
        ),
        migrations.CreateModel(
            name='ProductBrain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1, help_text='Increment on every edit for audit trail')),
                ('is_active', models.BooleanField(default=True)),
                ('sequence_rules', models.JSONField(blank=True, default=dict)),
                ('timing_rules', models.JSONField(blank=True, default=dict)),
                ('terminal_states', models.JSONField(blank=True, default=list)),
                ('escalation_rules', models.JSONField(blank=True, default=dict)),
                ('success_signals', models.JSONField(blank=True, default=dict)),
                ('call_eligibility', models.JSONField(blank=True, default=dict)),
                ('content_strategy', models.JSONField(blank=True, default=dict)),
                ('jobs', models.JSONField(blank=True, default=dict)),
                ('golden_set_path', models.CharField(blank=True, default='', max_length=500)),
                ('eval_threshold_pct', models.IntegerField(default=90)),
                ('call_script_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brains', to='campaigns.callscript')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brain', to='campaigns.product')),
                ('reply_prompt_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brains', to='campaigns.prompttemplate')),
            ],
            options={
                'db_table': 'product_brain',
                'ordering': ['product__slug'],
            },
        ),
        migrations.CreateModel(
            name='CampaignBrainOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overrides', models.JSONField(blank=True, default=dict)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brain_override', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'campaign_brain_override',
            },
        ),
    ]
