# Generated by Django 4.2.29 on 2026-04-21 08:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_prospect_reply_counters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.CharField(help_text='e.g. reply:interested, call:voicemail', max_length=200)),
                ('triggered_by', models.CharField(help_text='e.g. handle_replies, vapi_webhook, place_calls, admin, nudge_stale_leads', max_length=50)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='campaigns.prospect')),
            ],
            options={
                'db_table': 'prospect_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prospect', '-created_at'], name='prospect_ev_prospec_ee21fd_idx')],
            },
        ),
    ]
