# Generated by Django 4.2.29 on 2026-04-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_prospect_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='decision_maker_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='prospect',
            name='enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='enrichment_source',
            field=models.CharField(blank=True, default='', help_text='Source that provided decision maker data: companies_house, cro, website, google, bni', max_length=50),
        ),
        migrations.AddField(
            model_name='prospect',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
