# Generated by Django 4.2.30 on 2026-04-28 08:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0022_enrichment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateTimeField(db_index=True, help_text='UTC. Earliest moment process_call_queue may dispatch.')),
                ('reason', models.CharField(help_text='e.g. warm:reply:interested, warm:reply:question, warm:call_disposition', max_length=200)),
                ('attempts', models.IntegerField(default=0, help_text='Dispatch attempts. process_call_queue gives up at 5.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('done', 'Done'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('skip_reason', models.TextField(blank=True, default='', help_text='Populated when status=skipped or status=failed.')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('provider_call_id', models.CharField(blank=True, default='', help_text='Provider-returned call ID, e.g. Vapi call.id.', max_length=200)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_tasks', to='campaigns.prospect')),
                ('triggering_event', models.ForeignKey(blank=True, help_text='The lifecycle event that produced this task (audit link).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_tasks', to='campaigns.prospectevent')),
            ],
            options={
                'db_table': 'call_tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='call_tasks_status_7bfddb_idx'), models.Index(fields=['prospect', '-created_at'], name='call_tasks_prospec_fdb9eb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='calltask',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('prospect',), name='uniq_pending_call_task_per_prospect'),
        ),
    ]
