# Generated by Django 4.2.30 on 2026-04-28 09:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0023_add_call_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text="Short identifier, e.g. 'taggiq', 'canva', 'gmail'.", max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('transport', models.CharField(choices=[('stdio', 'Stdio (local subprocess)'), ('http', 'HTTP'), ('sse', 'Server-Sent Events'), ('streamable_http', 'Streamable HTTP')], default='http', max_length=32)),
                ('default_command_template', models.TextField(blank=True, default='', help_text='For stdio servers, the command (e.g. "npx -y @taggiq/mcp"). OrgMCPConnection.connection_config can override.')),
                ('documentation_url', models.URLField(blank=True, default='')),
                ('known_tools', models.JSONField(blank=True, default=list, help_text='Cached tool names for UI / allowlist editor. Authoritative source is the live MCP server.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'mcp_servers',
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='mcp_servers',
            field=models.JSONField(blank=True, default=list, help_text='Sprint 10. Per-campaign opt-in to MCP servers. List of OrgMCPConnection.slug values (e.g. ["taggiq", "canva"]). Empty = no MCP exposure (default). config_builder takes the intersection with active OrgMCPConnections in the campaign owner Organization.'),
        ),
        migrations.CreateModel(
            name='OrgMCPConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text="Human-readable slug for this connection within the Org. Default to MCPServer.slug; override (e.g. 'gmail-prakash', 'gmail-lisa') if the Org has multiple connections to the same server type.", max_length=64)),
                ('auth_secret_ref', models.CharField(blank=True, default='', help_text="Reference to where the auth secret lives, NOT the secret. Either an env var name (e.g. 'TAGGIQ_API_KEY_SKILLBLEND') or an AWS Secrets Manager ARN. Resolved at runtime by config_builder.", max_length=200)),
                ('connection_config', models.JSONField(blank=True, default=dict, help_text='Per-connection overrides: URL, headers (non-secret), environment vars, etc. Renders into the MCP config JSON.')),
                ('enabled_tools', models.JSONField(blank=True, default=list, help_text='Allowlist of tool names. Empty = use registry defaults (read-only safe set). Adding a write tool requires CTO + AI Architect review.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_status', models.CharField(default='unknown', help_text="'ok' | 'down' | 'unknown'. config_builder excludes 'down' connections for the next 1 hour after last failure.", max_length=32)),
                ('last_error', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_connections', to='campaigns.organization')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_connections', to='campaigns.mcpserver')),
            ],
            options={
                'db_table': 'org_mcp_connections',
                'ordering': ['organization', 'slug'],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='MCPSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_by', models.CharField(default='', help_text="e.g. 'handle_replies', 'process_call_queue', 'manual'.", max_length=64)),
                ('server_slugs', models.JSONField(blank=True, default=list, help_text='List of OrgMCPConnection slugs exposed in this session.')),
                ('claude_model', models.CharField(default='', max_length=100)),
                ('total_input_tokens', models.IntegerField(default=0)),
                ('total_output_tokens', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('num_turns', models.IntegerField(default=0)),
                ('tool_calls_count', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration_ms', models.IntegerField(default=0)),
                ('inbound_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_sessions', to='campaigns.inboundemail')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_sessions', to='campaigns.organization')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_sessions', to='campaigns.prospect')),
            ],
            options={
                'db_table': 'mcp_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MCPActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_name', models.CharField(help_text="Fully qualified, e.g. 'taggiq:create_quote_draft'.", max_length=200)),
                ('tool_args', models.JSONField(blank=True, default=dict, help_text='Truncated to 4KB. Sensitive fields redacted by audit.')),
                ('result', models.JSONField(blank=True, default=dict, help_text='Truncated to 4KB.')),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration_ms', models.IntegerField(default=0)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='campaigns.orgmcpconnection')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='campaigns.mcpsession')),
            ],
            options={
                'db_table': 'mcp_action_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mcpsession',
            index=models.Index(fields=['organization', '-created_at'], name='mcp_session_organiz_b3189e_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpsession',
            index=models.Index(fields=['triggered_by', '-created_at'], name='mcp_session_trigger_5a2e08_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpactionlog',
            index=models.Index(fields=['session', '-created_at'], name='mcp_action__session_c2b0da_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpactionlog',
            index=models.Index(fields=['tool_name', '-created_at'], name='mcp_action__tool_na_04bc5e_idx'),
        ),
    ]
