# Generated by Django 4.2.30 on 2026-04-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0024_add_mcp_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmcpconnection',
            name='auth_type',
            field=models.CharField(choices=[('static_bearer', 'Static bearer key (env var)'), ('oauth_cli', 'OAuth managed by Claude CLI (--user scope)'), ('none', 'No auth (public MCP server)')], default='static_bearer', help_text="Authentication mode. 'static_bearer' = env-var bearer key in our --mcp-config. 'oauth_cli' = OAuth managed by Claude CLI (claude mcp add --user); we don't include the server in our --mcp-config but the CLI inherits it from user scope. 'none' = public server, no auth.", max_length=32),
        ),
        migrations.AddField(
            model_name='orgmcpconnection',
            name='cli_user_scope_name',
            field=models.CharField(blank=True, default='', help_text='oauth_cli only: the name used when Prakash ran `claude mcp add --user <name>` in the cron container. Token state lives in the claude_auth Docker volume.', max_length=64),
        ),
        migrations.AlterField(
            model_name='orgmcpconnection',
            name='auth_secret_ref',
            field=models.CharField(blank=True, default='', help_text="static_bearer only: reference to where the auth secret lives (env var name like 'TAGGIQ_API_KEY_SKILLBLEND' or Secrets Manager ARN). Ignored for oauth_cli/none.", max_length=200),
        ),
    ]
