# Generated by Django 4.2.29 on 2026-05-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0026_prospect_status_bounced'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='domain_daily_limit',
            field=models.IntegerField(blank=True, help_text='Per-domain daily limit (for warmup). Leave blank for no limit. Set to 50 (week 1), 100 (week 2), 200 (week 3), then unset after warmup.', null=True),
        ),
    ]
