# Generated by Django 4.2.29 on 2026-04-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_prospect_event'),
        ('social_studio', '0002_add_visual_pipeline_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('product', 'platform', 'page_id')},
        ),
    ]
